### ISSUE TITLE
Firefox >> select component does not change ng-untouched/touched status of a form control

### ISSUE THREAD

**Issue by Blackbaud-EthanCranmer** [blackbaud/skyux-select-field#45]
### Expected behavior
When interacting with the skyux-select-field component with selectMode="multiple" in the browser Firefox, the component's ng-untouched status changes to ng-touched, regardless of if the value has changed.
### Actual behavior
When interacting with the skyux-select-field component with selectMode="multiple" in the browser Firefox, the component's ng-untouched status never changes to ng-touched..
### Steps to reproduce
Create a component that has a skyux-select-field with selectMode="multiple" and serve it.
Inspect the skyux-select-field and observe that it has ng-untouched as a class.
Interact with the object and select any amount or no values.
Observe that the component still has ng-untouched as a class and not ng-touched.
### Severity
High
### Impact
High

**Comment by Blackbaud-TrevorBurch** [comment]
This is not just happening in Firefox. I can reproduce this in Chrome. One note - if you inspect the element using Chrome dev tools it will switch to touched. However, if you find it in the elements and then interact normally with it then you can see this issue.

**Comment by Blackbaud-TrevorBurch** [comment]
Actually, on further inspection I am seeing `ng-touched` update in all browsers. However, it does not do this right away because we keep focus on the launch button once the modal closes and don't blur until the user manually blurs. On Firefox, it does not appear that the focus styles are working in multiple places. @Blackbaud-ToddRoberts lets touch base about this.

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.4.1`
